config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :hikes, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :breaks, only: [:index, :show, :new, :create, :edit, :update]
  resources :trails, only: [:index, :show, :create, :new]
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :shelters, only: [:index, :show, :new, :create]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/shelter.rb
class Shelter < ApplicationRecord
  belongs_to :trail
  has_many :users, through: :breaks
  has_many :breaks

  #returns breaks at a specific shelter
  def breaks_at_shelter
    Break.completed_breaks.select do |b|
      b.shelter_id == self.id
    end
  end

  def review_blank
    @review_array = self.breaks_at_shelter.collect do |b|
      if b.review != ""
        "#{b.user.username} - '#{b.review}' -- #{b.rating}"
      else
        nil
      end
    end
    @review_array.compact
  end

  def self.most_visited_shelter
    Shelter.all.max_by do |shelter|
    shelter.breaks_at_shelter.count
    end
  end

  def self.most_visited_shelter_count
    Shelter.most_visited_shelter.breaks_at_shelter.count
  end

  def self.percentage_of_visitors
    (Shelter.most_visited_shelter_count / Shelter.all.count.to_f*100).round(2)
  end

  def shelter_rating
    ratingsArr = self.breaks_at_shelter.collect do |br|
      br.rating
    end

    if ratingsArr.any?
      return (ratingsArr.sum/ratingsArr.size.to_f).round(1)
    else
      return "No Ratings!"
    end
  end

  def self.rated_shelters
    Shelter.all.select do |shelter|
      shelter.shelter_rating != "No Ratings!"
    end
  end

  def avg_rating
    self.all_shelter_ratings.reduce(:+)/self.all_shelter_ratings.length.to_f
  end

  def self.highest_rated_shelter
    # byebug

    if self.rated_shelters.any?
      return self.rated_shelters.max_by do |shelter|
        shelter.shelter_rating
      end
    else 
      Shelter.last
    end
  end
end

app/controllers/shelters_controller.rb
class SheltersController < ApplicationController

  before_action :get_shelter, only: [:show]
  before_action :admin_authorize, only: [:create, :new]
  before_action :authorized

  def index
    @shelters = Shelter.all
  end

  def show
  end

  def new
    @shelter = Shelter.new
  end

  def create
    @shelter = Shelter.new(shelter_params)
    if @shelter.save
      redirect_to @shelter
    else
      render :new
    end
  end

  private

  def get_shelter
    @shelter = Shelter.find(params[:id])
  end

  def shelter_params
    params.require(:shelter).permit(:name, :location, :description, :trail_id)
  end

end

app/helpers/shelters_helper.rb
module SheltersHelper
end

app/views/shelters/index.html.erb
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm">
      <h1>Shelters to Explore</h1>
    </div>
  </div><br><br>
  <div class="row">
    <div class="col-sm">
      <h2>Most Visited Shelter: <%= link_to Shelter.most_visited_shelter.name, Shelter.most_visited_shelter %> <%= Shelter.percentage_of_visitors %>%</h2>
    </div>
    <div class="col-sm">
      <h2>Highest Rated Shelter: <%= link_to Shelter.highest_rated_shelter.name, Shelter.highest_rated_shelter %> <%= Shelter.highest_rated_shelter.shelter_rating %>/10</h2>
    </div>
  </div>
</div>

<table class="table table-bordered table-hover">
<thead>
  <tr>
    <th>Shelter Name</th>
    <th>Trail Name</th>
    <th>Location on Trail</th>
    <th>Description</th>
    <th>Break</th>
  </tr>
</thead>

<tbody>
  <% @shelters.each do |shelter| %>
    <tr>
      <td><%= link_to shelter.name, shelter %></td>
      <td><%= link_to shelter.trail.name, shelter.trail%></td>
      <td><%= shelter.location %></td>
      <td><%= shelter.description %></td>
      <td><%= link_to "Start Break", new_break_path %></td>
    </tr>
  <% end %>
</tbody>

</table>

app/views/shelters/new.html.erb
<%= form_for @shelter do |f| %>
    <% if @shelter.errors.any? %>
<ul>
   <% @shelter.errors.full_messages.each do |m| %>
  <li><%= m %></li>
    <% end %>
</ul>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.collection_select(:trail_id, Trail.all, :id, :name, prompt: "Trail Name") %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/shelters/show.html.erb
<br>
<div class="col-sm-4">
<h1><%= @shelter.name %></h1>
<div class="img-fluid">

<ul class="list-group">

<li class="list-group-item">Location: <%= @shelter.location %></li>
<li class="list-group-item">Description: <%= @shelter.description %></li>
<li class="list-group-item">Shelter Rating: <%= @shelter.shelter_rating %></li>
</ul>
</br>

<ul class="list-group">
<h5>Shelter Reviews:</h5>

<% @shelter.review_blank.each do |review|%>
    <li class="list-group-item"><%= review %></li>
<% end %>

</ul> 
<br>
<button type="button" class="btn btn-outline-info"><%= link_to "Start Break", new_break_path %></button>

<br><br>

<hr>


<button type="button" class="btn btn-outline-success"><%= link_to "All Shelters", shelters_path %></button>