config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :hikes, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :breaks, only: [:index, :show, :new, :create, :edit, :update]
  resources :trails, only: [:index, :show, :create, :new]
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :shelters, only: [:index, :show, :new, :create]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/break.rb
class Break < ApplicationRecord
  belongs_to :user
  belongs_to :shelter
  validates :rating, presence: true, on: :update

  def self.completed_breaks
    Break.all.select do |br|
      br.updated_at != br.created_at
    end
  end

  def start_time
    d = DateTime.parse(self.created_at.to_s)
    @start_time = d.strftime('%I:%M %p')
  end

  def end_time
    if self.updated_at == self.created_at
      @end_time = self.updated_at = "Pending"
    else
      d = DateTime.parse(self.updated_at.to_s)
      @end_time = d.strftime('%I:%M %p')
    end
  end

  def length_of_break
    if @end_time == "Pending"
      return nil
    else
      d = DateTime.parse((self.created_at - self.updated_at).to_s)
      d.strftime('%M minutes')
    end
  end
end

app/controllers/breaks_controller.rb
class BreaksController < ApplicationController

  before_action :get_break, only: [:show, :edit, :update]
  before_action :authorized

  def show
  end

  def new
    @break = Break.new
  end

  def create
    @break = Break.new(break_params)
    if @break.save
      redirect_to @break
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @break.update(break_update_params)
      redirect_to @break
    else
      render :edit
    end
  end

  private

  def get_break
    @break = Break.find(params[:id])
  end

  def break_params
    params.require(:break).permit(:user_id, :shelter_id, :start_time).merge(review: nil, rating: 1, end_time: nil)
  end

  def break_update_params
    params.require(:break).permit(:user_id, :shelter_id, :start_time, :end_time, :review, :rating)
  end
end

app/helpers/breaks_helper.rb
module BreaksHelper
end

app/views/breaks/edit.html.erb
<%= form_for @break do |f| %>
    <% if @break.errors.any? %>
<ul>
   <% @break.errors.full_messages.each do |m| %>
  <li><%= m %></li>
    <% end %>
</ul>
  <% end %>

  <%= f.label :review, "Review Your Break!" %><br><br>
  <%= f.text_area :review %><br>
  <%= f.label :rating, "Rate Your Break!" %>
  <%= f.select :rating, (1..10), :include_blank => "Please Rate" %>
  <%= f.submit "Leave Review" %>
<% end %>

app/views/breaks/show.html.erb
<br>
<div class="col-sm-4">
<h2>Break Has Begun at <%= link_to @break.shelter.name %></h2>
<div class="img-fluid">

<ul class="list-group">
<li class="list-group-item">Start Time: <%= @break.start_time %></li>
<li class="list-group-item">End Time: <%= @break.end_time %></li>
<li class="list-group-item">Total Break Time: <%= @break.length_of_break %></li>
<li class="list-group-item">Review: <%= @break.review %></li>
<li class="list-group-item">Rating: <%= @break.rating %></li>

</ul>

<br>

<button type="button" class="btn btn-outline-danger"><%= link_to "End Break", edit_break_path(@break) %></button>