config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :hikes, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :breaks, only: [:index, :show, :new, :create, :edit, :update]
  resources :trails, only: [:index, :show, :create, :new]
  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :shelters, only: [:index, :show, :new, :create]



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/trail.rb
class Trail < ApplicationRecord
  has_many :shelters
  has_many :hikes
  has_many :users, through: :hikes

  def hikes_on_trail
    Hike.completed_hikes.select do |t|
      t.trail_id == self.id
    end
  end

  def trail_rating
    trailRatingArr = self.hikes_on_trail.collect do |hike|
      hike.rating
    end
    if trailRatingArr.any?
      return (trailRatingArr.sum/trailRatingArr.size.to_f).round(1)
    else
      return "No Ratings!"
    end
  end


  def all_trail_ratings
    a = Hike.all.map do |b|
      b.rating
    end
    a.compact!
  end

  def users_on_trail
    a = self.hikes_on_trail.collect do |hike|
      hike.user
    end
    a.uniq
  end

  def avg_rating
    self.all_trail_ratings.reduce(:+)/self.all_trail_ratings.length.to_f
  end

  def self.rated_trails
    Trail.all.select do |trail|
      trail.trail_rating != "No Ratings!"
    end
  end

  def self.highest_rated_trail
    if self.rated_trails.any?
      return self.rated_trails.max_by do |trail|
        trail.trail_rating
      end
    else 
      Trail.last
    end
  end

 

  def self.most_difficult_trail
    Trail.all.max_by do |trail|
    trail.difficulty_level
    end
  end

end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController

  before_action :get_trail, only: [:show]
  before_action :authorized, except: [:index]

  def index
    @trails = Trail.all
  end

  def show
  end

  def new
    @trail = Trail.new
  end

  def create
    @trail = Trail.new(trail_params)
    if @trail.save
      redirect_to @trail
    else
      render :new
    end
  end

  private

  def get_trail
    @trail = Trail.find(params[:id])
  end

  def trail_params
    params.require(:trail).permit(:description, :difficulty_level, :distance, :name)
  end
end

app/helpers/trails_helper.rb
module TrailsHelper
end

app/views/trails/index.html.erb
<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-sm">
      <h1 class="text-center">Choose a Trail</h1>
    </div>
  </div><br><br>
  <div class="row">
    <div class="col-sm">
      <h3>Top Rated Trail: <%= link_to Trail.highest_rated_trail.name, Trail.highest_rated_trail %> <%= Trail.highest_rated_trail.trail_rating %>/10</h3>
    </div>
  </div>
</div>
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th>Trail Name</th>
            <th>Distance</th>
            <th>Difficulty Level</th>
            <th>Trail Rating</th>
            <th>Hike</th>
          </tr>
        </thead>

        <tbody>
          <% @trails.each do |trail| %>
          <tr>
            <td><%= link_to trail.name, trail %></td>
            <td><%= trail.distance %></td>
            <td><%= trail.difficulty_level %></td>
            <td><%= trail.trail_rating %></td>
            <td><%= link_to "Start Hike", new_hike_path %></td>
          </tr>
          <% end %>
        </tbody>

      </table>

app/views/trails/new.html.erb
<h1>Create a Trail</h1>

<%= form_for @trail do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :distance %>
  <%= f.number_field :distance, :step => 0.01 %>
  <%= f.label :difficulty_level %>
  <%= f.select :difficulty_level, (1..10) %><br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit %>
<% end %>

app/views/trails/show.html.erb
<br>
<div class="col-sm-4">
<h1><%= @trail.name %></h1>
<div class="img-fluid">

<ul class="list-group">
<li class="list-group-item">Description: <%= @trail.description %></li>
<li class="list-group-item">Distance: <%= @trail.distance %></li>
<li class="list-group-item">Difficulty Level: <%= @trail.difficulty_level %></li>
<li class="list-group-item">Hikes On Trail: <%= @trail.hikes_on_trail.count %></li>

<li class="list-group-item">Shelters on <%= @trail.name %>:

  <% @trail.shelters.each do |shelter| %>
  <button type="button" class="btn btn-outline-warning"><%= link_to shelter.name, shelter %></button></li>
  <% end %>


<li class="list-group-item">Previous Hikers
 
  <% @trail.users_on_trail.each do |user| %>
  <button type="button" class="btn btn-outline-warning"><%= link_to user.username, user %></button></li>
  <% end %>


</ul>
<hr>
<button type="button" class="btn btn-outline-success"><%= link_to "Back to trail list", trails_path %></button>